// src/app/layout.js (Servidor)
import './globals.css';
import ClientWrapper from '@/components/clientbottom';

export const metadata = {
  title: "Hospital",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <ClientWrapper>{children}</ClientWrapper> {/* Aquí se renderiza el layout sin lógica de cliente */}
      </body>
    </html>
  );
}
